// lib/mockData.ts

export const mockPharmacy = {
  id: "PHARM-001",
  name: "HealthPlus Pharmacy",
  email: "healthplus@pharmacy.com",
  phone: "+94 77 123 4567",
  address: "123 Main Street, Colombo 03, Sri Lanka",
  isAvailable: true,
};

export const mockMedicines = [
  {
    id: "MED-001",
    name: "Paracetamol",
    genericName: "Paracetamol",
    brandName: "Panadol",
    category: "tablets",
    doseForm: "Tablet",
    strength: "500mg",
    price: 150.00,
    stockQty: 250,
    minQty: 50,
    expiryDate: "2025-12-31",
    manufacturer: "GSK",
    requiresPrescription: false,
    lowStock: false,
    soonToExpire: false,
  },
  {
    id: "MED-002",
    name: "Amoxicillin",
    genericName: "Amoxicillin",
    brandName: "Amoxil",
    category: "capsules",
    doseForm: "Capsule",
    strength: "250mg",
    price: 280.00,
    stockQty: 120,
    minQty: 30,
    expiryDate: "2025-08-15",
    manufacturer: "Pfizer",
    requiresPrescription: true,
    lowStock: false,
    soonToExpire: false,
  },
  {
    id: "MED-003",
    name: "Ibuprofen",
    genericName: "Ibuprofen",
    brandName: "Brufen",
    category: "tablets",
    doseForm: "Tablet",
    strength: "400mg",
    price: 220.00,
    stockQty: 180,
    minQty: 50,
    expiryDate: "2026-03-20",
    manufacturer: "Abbott",
    requiresPrescription: false,
    lowStock: false,
    soonToExpire: false,
  },
  {
    id: "MED-004",
    name: "Cough Syrup",
    genericName: "Dextromethorphan",
    brandName: "Benadryl",
    category: "syrup",
    doseForm: "Syrup",
    strength: "100ml",
    price: 450.00,
    stockQty: 45,
    minQty: 20,
    expiryDate: "2025-06-30",
    manufacturer: "Johnson & Johnson",
    requiresPrescription: false,
    lowStock: false,
    soonToExpire: true,
  },
  {
    id: "MED-005",
    name: "Insulin",
    genericName: "Insulin Glargine",
    brandName: "Lantus",
    category: "injection",
    doseForm: "Injection",
    strength: "100 units/ml",
    price: 3500.00,
    stockQty: 15,
    minQty: 20,
    expiryDate: "2025-11-15",
    manufacturer: "Sanofi",
    requiresPrescription: true,
    lowStock: true,
    soonToExpire: false,
  },
  {
    id: "MED-006",
    name: "Omeprazole",
    genericName: "Omeprazole",
    brandName: "Losec",
    category: "capsules",
    doseForm: "Capsule",
    strength: "20mg",
    price: 180.00,
    stockQty: 200,
    minQty: 40,
    expiryDate: "2026-09-10",
    manufacturer: "AstraZeneca",
    requiresPrescription: false,
    lowStock: false,
    soonToExpire: false,
  },
  {
    id: "MED-007",
    name: "Cetirizine",
    genericName: "Cetirizine",
    brandName: "Zyrtec",
    category: "tablets",
    doseForm: "Tablet",
    strength: "10mg",
    price: 95.00,
    stockQty: 300,
    minQty: 60,
    expiryDate: "2026-04-25",
    manufacturer: "UCB",
    requiresPrescription: false,
    lowStock: false,
    soonToExpire: false,
  },
  {
    id: "MED-008",
    name: "Azithromycin",
    genericName: "Azithromycin",
    brandName: "Zithromax",
    category: "tablets",
    doseForm: "Tablet",
    strength: "500mg",
    price: 520.00,
    stockQty: 18,
    minQty: 25,
    expiryDate: "2025-07-18",
    manufacturer: "Pfizer",
    requiresPrescription: true,
    lowStock: true,
    soonToExpire: true,
  },
];

export const mockOrders = [
  {
    id: "ORD-001",
    customerName: "John Doe",
    customerPhone: "+94 77 111 2222",
    orderDate: new Date(2024, 11, 15, 10, 30).toISOString(),
    status: "pending" as const,
    items: [
      { medicineId: "MED-001", medicineName: "Paracetamol", quantity: 2, price: 150 },
      { medicineId: "MED-003", medicineName: "Ibuprofen", quantity: 1, price: 220 },
    ],
    totalAmount: 520.00,
    deliveryAddress: "45 Galle Road, Colombo 03",
    paymentMethod: "Cash on Delivery",
  },
  {
    id: "ORD-002",
    customerName: "Jane Smith",
    customerPhone: "+94 77 333 4444",
    orderDate: new Date(2024, 11, 15, 11, 15).toISOString(),
    status: "accepted" as const,
    items: [
      { medicineId: "MED-002", medicineName: "Amoxicillin", quantity: 3, price: 280 },
    ],
    totalAmount: 840.00,
    deliveryAddress: "78 Duplication Road, Colombo 04",
    paymentMethod: "Card",
  },
  {
    id: "ORD-003",
    customerName: "Robert Kumar",
    customerPhone: "+94 77 555 6666",
    orderDate: new Date(2024, 11, 15, 14, 45).toISOString(),
    status: "in-progress" as const,
    items: [
      { medicineId: "MED-004", medicineName: "Cough Syrup", quantity: 2, price: 450 },
      { medicineId: "MED-007", medicineName: "Cetirizine", quantity: 1, price: 95 },
    ],
    totalAmount: 995.00,
    deliveryAddress: "123 Kandy Road, Colombo 07",
    paymentMethod: "Cash on Delivery",
  },
  {
    id: "ORD-004",
    customerName: "Sarah Fernando",
    customerPhone: "+94 77 777 8888",
    orderDate: new Date(2024, 11, 14, 16, 20).toISOString(),
    status: "completed" as const,
    items: [
      { medicineId: "MED-006", medicineName: "Omeprazole", quantity: 2, price: 180 },
    ],
    totalAmount: 360.00,
    deliveryAddress: "56 Baseline Road, Colombo 09",
    paymentMethod: "Card",
  },
];

export const mockAnalytics = {
  totalMedicines: mockMedicines.length,
  activeMedicines: mockMedicines.filter(m => m.stockQty > 0).length,
  lowStockCount: mockMedicines.filter(m => m.lowStock).length,
  expiringCount: mockMedicines.filter(m => m.soonToExpire).length,
  totalInventoryValue: mockMedicines.reduce((sum, m) => sum + (m.price * m.stockQty), 0),
  pendingOrders: mockOrders.filter(o => o.status === 'pending').length,
};

export const mockNotifications = [
  {
    id: "NOT-001",
    type: "low_stock",
    title: "Low Stock Alert",
    message: "Insulin is running low (15 units remaining)",
    timestamp: new Date(2024, 11, 15, 9, 0).toISOString(),
    read: false,
  },
  {
    id: "NOT-002",
    type: "expiry",
    title: "Expiry Alert",
    message: "Cough Syrup expires in 30 days",
    timestamp: new Date(2024, 11, 15, 8, 30).toISOString(),
    read: false,
  },
  {
    id: "NOT-003",
    type: "order",
    title: "New Order",
    message: "New order from John Doe (#ORD-001)",
    timestamp: new Date(2024, 11, 15, 10, 30).toISOString(),
    read: true,
  },
];